baseURL = 'https://frontier.scetrov.live/'
languageCode = 'en-us'
title = 'Unofficial EVE Frontier Development Notes'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  editURL = 'https://github.com/Scetrov/frontier.scetrov.live/edit/main/content/${FilePath}'
  themeVariant = 'frontier-dark'
  images = ['images/hero.png']

[markup]
  [markup.highlight]
    noClasses = false
